application: scriptletsapp
version: 2
runtime: python
api_version: 1

handlers:
- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico
- url: /robots.txt
  static_files: static/robots.txt
  upload: static/robots.txt
- url: /static
  static_dir: static
- url: /view.*
  script: legacy.py
- url: /code.*
  script: legacy.py
- url: /run.*
  script: legacy.py
- url: /.*
  script: main.py
